plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.113'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

group = 'io.github.xaeka'
version = '1.0.2'

base {
    archivesName = 'unfixmc181190'
}

neoForge {
    version = '21.11.42'

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        unfixmc181190 {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
}
